spring:
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  port: 8080
  use-forward-headers: true
  forward-headers-strategy: framework

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  version: "1"

files:
  path:
    to-load: "example.csv,example_small.csv"
